
swagger-aggregate:
  resources:
    - name: test1
      url: http://127.0.0.1:8081/v2/api-docs
      version: 2.0
    - name: test2
      url: http://127.0.0.1:8082/v3/api-docs
      version: 3.0



