swagger-aggregate:
  resources:
    - name: testV2
      url: http://127.0.0.1:8082/v2/api-docs
      version: 2.0
    - name: testV3
      url: http://127.0.0.1:8083/v3/api-docs
      version: 3.0.3



